# Generated by Django 4.1.7 on 2023-05-01 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apprentissage1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='nomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champ1', models.CharField(max_length=45)),
                ('champ2', models.CharField(max_length=45)),
                ('champ3', models.BooleanField(default=True)),
                ('champ4', models.DateField()),
            ],
            options={
                'verbose_name': 'Django Admin Tutorial',
                'verbose_name_plural': 'Django Admin Tutorials',
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
