# Generated by Django 4.2 on 2023-05-05 19:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apprentissage1', '0003_course_hours_course_link_course_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_de_naissance',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
